questions =  [
    {"id": 0, "question": "i like among us", "effects": {"right": -1}},
    {"id": 1, "question": "i like goosegooseduck", "effects": {"right": 1}},
    {"id": 2, "question": "i am a fan of thomas", "effects": {"auth": 1}},
    {"id": 3, "question": "i am an avid arcade classics fan?", "effects": {"auth": 1}},
    {"id": 4, "question": "i have sex with many people", "effects": {"auth": 1}},
    {"id": 5, "question": "i like chillis", "effects": {"right": 1}},
    {"id": 6, "question": "i like summer more than winter", "effects": {"right": 1}},
    {"id": 7, "question": "i like snacking", "effects": {"right": -1}},
    {"id": 8, "question": "last person i sexed was a mother", "effects": {"auth": -1}},
    {"id": 9, "question": "i think gingers have souls", "effects": {"right": -1}},
    {"id": 10, "question": "i have tried out thomas' startpage (latest update)", "effects": {"auth": 1}},
    {"id": 11, "question": "cum!", "effects": {"prog": 1}},
    {"id": 12, "question": "i would sex adam", "effects": {"prog": 1}},
    {"id": 13, "question": "i like anime", "effects": {"prog": -1}},
    {"id": 14, "question": "i like genshit impact", "effects": {"auth": -1}},
    {"id": 15, "question": "i shitted my pants before", "effects": {"prog": 1}},
    {"id": 16, "question": "i am a war criminal", "effects": {"prog": 1}},
    {"id": 17, "question": "i enjoy shrek", "effects": {"auth": 1}},
    {"id": 18, "question": "i like to eat barry bee benson's ass", "effects": {"right": -1}},
    {"id": 19, "question": "i scream hogrida at the top of my lungs everytime i attack an ukranian war lord (louder at night)", "effects": {"auth": 1}},
];
